services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    
  discord-bot:
    container_name: discord-bot
    build:
      context: .
      dockerfile: ./apps/discord-bot/Dockerfile
    restart: always
    env_file: ./apps/discord-bot/.env
      
volumes:
  db:

